POST http://localhost:8080/api/restaurants
Content-Type: application/json

{
  "userId": 1,
  "name": "Restaurante Exemplo",
  "cnpj": "11222333000181"
}


---

### Listar todos os restaurantes
GET http://localhost:8080/api/restaurants
